# Generated by Django 5.2.4 on 2026-05-28 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0002_news_relevance_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(default="Tamil Nadu", max_length=100)),
                ("salary_text", models.CharField(blank=True, max_length=255)),
                ("salary_min", models.IntegerField(blank=True, null=True)),
                ("salary_max", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="INR", max_length=20)),
                (
                    "pay_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("daily", "Daily"),
                            ("hourly", "Hourly"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("apprenticeship", "Apprenticeship"),
                            ("government", "Government"),
                            ("private", "Private"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("experience", models.CharField(blank=True, max_length=255)),
                ("education", models.CharField(blank=True, max_length=255)),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="IT, manufacturing, healthcare, teaching, government, sales, etc.",
                        max_length=100,
                    ),
                ),
                ("apply_url", models.URLField(blank=True, max_length=1000)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-posted_at", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="contentitem",
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["source_type", "name"]},
        ),
        migrations.RenameIndex(
            model_name="contentitem",
            new_name="aggregator__content_32f07f_idx",
            old_name="aggregator__content_a608f8_idx",
        ),
        migrations.RenameIndex(
            model_name="contentitem",
            new_name="aggregator__source__d33a50_idx",
            old_name="aggregator__source__2e45fd_idx",
        ),
        migrations.RenameIndex(
            model_name="rawitem",
            new_name="aggregator__source__919817_idx",
            old_name="aggregator__source__3533f1_idx",
        ),
        migrations.RenameIndex(
            model_name="rawitem",
            new_name="aggregator__content_6b2ce1_idx",
            old_name="aggregator__content_bce448_idx",
        ),
        migrations.RenameIndex(
            model_name="rawitem",
            new_name="aggregator__publish_2e525b_idx",
            old_name="aggregator__publish_8f4ce8_idx",
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("youtube_video", "YouTube Video"),
                    ("tweet", "Tweet"),
                    ("job_post", "Job Post"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="crawl_method",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("html", "HTML"),
                    ("youtube_api", "YouTube API"),
                    ("youtube_rss", "YouTube RSS"),
                    ("x_api", "X API"),
                    ("job_rss", "Job RSS"),
                    ("job_html", "Job HTML"),
                    ("job_csv", "Job CSV"),
                    ("job_api", "Job API"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("news_site", "News Site"),
                    ("youtube", "YouTube"),
                    ("x", "X/Twitter"),
                    ("jobs", "Jobs"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="content_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="aggregator.contentitem",
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["district", "posted_at"], name="aggregator__distric_78f84d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["category", "posted_at"], name="aggregator__categor_01edc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["salary_min", "salary_max"],
                name="aggregator__salary__33e87b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["is_active", "posted_at"], name="aggregator__is_acti_76db59_idx"
            ),
        ),
    ]
