# Generated by Django 5.2.4 on 2026-05-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0003_joblisting_alter_contentitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="primary_topic",
            field=models.CharField(
                choices=[
                    ("politics", "Politics"),
                    ("government_policy", "Government & Policy"),
                    ("assembly_watch", "Assembly Watch"),
                    ("economy_welfare", "Economy & Welfare"),
                    ("education", "Education"),
                    ("health", "Health"),
                    ("law_order", "Law & Order"),
                    ("infrastructure_transport", "Infrastructure & Transport"),
                    ("agriculture_farmers", "Agriculture & Farmers"),
                    ("cinema_culture", "Cinema & Culture"),
                    ("district_local", "District & Local Governance"),
                    ("jobs_employment", "Jobs & Employment"),
                    ("general", "General"),
                ],
                db_index=True,
                default="general",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="secondary_topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="report_sections",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="last_validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="link_status",
            field=models.CharField(
                choices=[
                    ("unchecked", "Unchecked"),
                    ("valid", "Valid"),
                    ("broken", "Broken"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="unchecked",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="qualification_level",
            field=models.CharField(
                choices=[
                    ("below_10th", "Below 10th"),
                    ("10th_pass", "10th Pass"),
                    ("12th_pass", "12th Pass"),
                    ("iti_diploma", "ITI / Diploma"),
                    ("graduate", "Graduate"),
                    ("postgraduate", "Postgraduate"),
                    ("professional", "Professional Degree"),
                    ("phd", "PhD"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="qualification_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="recruiting_body",
            field=models.CharField(
                choices=[
                    ("tnpsc", "TNPSC"),
                    ("mrb", "Medical Recruitment Board"),
                    ("trb", "Teachers Recruitment Board"),
                    ("tnusrb", "Police / Uniformed Services"),
                    ("tn_govt_department", "Tamil Nadu Government Department"),
                    ("central_govt", "Central Government"),
                    ("psu_bank_railway", "PSU / Bank / Railway"),
                    ("apprenticeship", "Apprenticeship"),
                    ("private_verified", "Verified Private Jobs"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Sector/family: IT, healthcare, teaching, manufacturing, government, sales, etc.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="crawl_method",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("html", "HTML"),
                    ("youtube_api", "YouTube API"),
                    ("youtube_rss", "YouTube RSS"),
                    ("x_api", "X API"),
                    ("job_rss", "Job RSS"),
                    ("job_html", "Job HTML"),
                    ("job_csv", "Job CSV"),
                    ("job_api", "Job API"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="rss_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("news_site", "News Site"),
                    ("youtube", "YouTube"),
                    ("x", "X/Twitter"),
                    ("government", "Government Source"),
                    ("assembly", "Assembly Source"),
                    ("party", "Party / Political Organization"),
                    ("commentary", "Commentary"),
                    ("jobs", "Jobs"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["primary_topic", "published_at"],
                name="aggregator__primary_46aecc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["recruiting_body", "posted_at"],
                name="aggregator__recruit_014b68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["qualification_level", "posted_at"],
                name="aggregator__qualifi_6bfb42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["deadline"], name="aggregator__deadlin_8e5632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["link_status"], name="aggregator__link_st_58cbf4_idx"
            ),
        ),
    ]
