# Generated by Django 5.2.4 on 2026-06-01 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0004_contentitem_primary_topic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_en", models.TextField(blank=True, default="")),
                ("summary_ta", models.TextField(blank=True, default="")),
                ("main_topics", models.JSONField(blank=True, default=list)),
                ("key_issues", models.JSONField(blank=True, default=list)),
                ("stance", models.CharField(blank=True, default="", max_length=32)),
                ("stance_detail", models.TextField(blank=True, default="")),
                ("sentiment", models.CharField(blank=True, default="", max_length=32)),
                ("video_count", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest",
                        to="aggregator.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
