# Generated by Django 5.2.4 on 2026-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0005_channeldigest"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("annual", "Annual"),
                ],
                db_index=True,
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="report_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="dailyreport",
            constraint=models.UniqueConstraint(
                fields=("report_date", "period"), name="unique_report_date_period"
            ),
        ),
    ]
