# Generated by Django 5.2.4 on 2026-06-08 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aggregator",
            "0006_dailyreport_period_alter_dailyreport_report_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "keywords",
                    models.TextField(
                        help_text="Comma-separated keywords, people, parties, districts, or topics to watch."
                    ),
                ),
                (
                    "match_mode",
                    models.CharField(
                        choices=[("any", "Any keyword"), ("all", "All keywords")],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("news_site", "News Site"),
                            ("youtube", "YouTube"),
                            ("x", "X/Twitter"),
                            ("government", "Government Source"),
                            ("assembly", "Assembly Source"),
                            ("party", "Party / Political Organization"),
                            ("commentary", "Commentary"),
                            ("jobs", "Jobs"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "primary_topic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("politics", "Politics"),
                            ("government_policy", "Government & Policy"),
                            ("assembly_watch", "Assembly Watch"),
                            ("economy_welfare", "Economy & Welfare"),
                            ("education", "Education"),
                            ("health", "Health"),
                            ("law_order", "Law & Order"),
                            ("infrastructure_transport", "Infrastructure & Transport"),
                            ("agriculture_farmers", "Agriculture & Farmers"),
                            ("cinema_culture", "Cinema & Culture"),
                            ("district_local", "District & Local Governance"),
                            ("jobs_employment", "Jobs & Employment"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                ("minimum_relevance", models.FloatField(default=0.0)),
                (
                    "notification_channel",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("email", "Email")],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "updated_at"],
                        name="aggregator__is_acti_fb13ea_idx",
                    ),
                    models.Index(
                        fields=["source_type", "primary_topic"],
                        name="aggregator__source__102197_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("snippet", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "matched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="aggregator.contentitem",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="aggregator.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "matched_at"],
                        name="aggregator__status_9a36e2_idx",
                    ),
                    models.Index(
                        fields=["rule", "matched_at"],
                        name="aggregator__rule_id_03c362_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "content_item"),
                        name="unique_alert_rule_content_item",
                    )
                ],
            },
        ),
    ]
