# Generated by Django 5.2.4 on 2026-06-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0007_alertrule_alertevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="E.164 format, e.g. +91XXXXXXXXXX, for WhatsApp delivery.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="source",
            name="extract_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Auto / default"),
                    ("listing_html", "HTML listing page"),
                    ("listing_pdf", "Listing → PDF notifications"),
                    ("spa_api", "JS app (needs API or headless browser)"),
                    ("feed", "RSS / Atom feed"),
                ],
                default="auto",
                help_text="How to extract structured items. Govt boards are listing_pdf; NCS/Apprenticeship are spa_api.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="notification_channel",
            field=models.CharField(
                choices=[
                    ("in_app", "In-app"),
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="in_app",
                max_length=20,
            ),
        ),
    ]
